languageCode = "en"
languageName = "English"
weight = 1
title = "Cybersecurity Writeups"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
# logo = "img/logo.png"
description = "My awesome website"
copyright = "Copy, _right?_ :thinking_face:"
dateFormat = "2 January 2006"