languageCode = "en"
languageName = "English"
weight = 1
title = "Cybersecurity Writeups"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
# logo = "img/logo.png"
description = "A collection of writeups and resources related to cybersecurity."
copyright = ""
dateFormat = "2 January 2006"