languageCode = "en"
languageName = "English"
weight = 1
title = "Daksh"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
# logo = "img/logo.png"
description = "My awesome website"
copyright = "Copy, _right?_ :thinking_face:"
dateFormat = "2 January 2006"

[params.author]
name = "Daksh"
image = "img/avatar.png"
links = [
    { link = "https://dakshthapar.com" },
    { github = "https://github.com/DakshRocks21" },
]